version: '3.7'

volumes:
    database:
        driver: local

services:
    database:
        image: mysql:5.7
        environment:
          - MYSQL_DATABASE:${DB_DATABASE:-readers_club_dev}
          - MYSQL_USER=${DB_USERNAME:-readers_club}
          - MYSQL_PASSWORD=${DB_PASSWORD:-12345678}
          - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-12345678}
          - LANG=C.UTF_8
          - TZ=${DB_TIMEZONE:-America/Sao_Paulo}
        volumes:
          - ${DB_DATA_PATH:-./storage/docker}/mysql:/var/lib/mysql
        ports:
          - "${DB_PORT}:3306"
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--skip-character-set-client-handshake']