version: '3.7'

volumes:
    mysql:
        driver: local

services:
    mysql:
        image: mysql:5.7
        environment:
          - MYSQL_USER=${DB_USERNAME}
          - MYSQL_PASSWORD=${DB_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
          - LANG=C.UTF_8
          - TZ=${DB_TIMEZONE}
        volumes:
          - ${DB_DATA_PATH}/mysql:/var/lib/mysql
        ports:
          - "${DB_PORT}:3306"
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--skip-character-set-client-handshake']