@startuml User book CRUD diagram


set namespaceSeparator ::

class HomeIndexPublicController extends Inertia::Controller {}

abstract UserAreaController extends Routing::controller {
    - BookService service
}
note top of BookService
    both get and store are colled
    by BookGetUserAreaController
endnote
class BookService {
    - Book $service
    + Collection list
    + void delete
    + UserBook get
    + UserBook store
}
class BookListUserAreaController extends UserAreaController
class BookStoreUserAreaController {
    + __invoke(StoreBookUserRequest $request)
}
class BookDeleteUserAreaController extends UserAreaController {}
class BookGetUserAreaController extends UserAreaController {
    + __invoke(? UserBook $userBook)
}
class StoreBookUserRequest extends FormRequest {
    + ISBN_10
    + ISBN_13
    + title
    + authors[]
    + pageCount
    + thumbnail
}

UserAreaController -right- BookService
BookStoreUserAreaController -left- BookService
StoreBookUserRequest *-- BookStoreUserAreaController

@enduml
